### PR TITLE
milestone 4 done

### PR DESCRIPTION
**Pull request by jasonyu0705**
## Developer: Jason Yu

Closes #{ISSUE NUMBER HERE}

### Pull Request Summary

all milestones done

deployment link: https://bootcamp-project-2024-zeta.vercel.app

### Pull Request Readiness Checklist

- [X] Code is neat, readable, and works
- [X] Comments are appropriate
- [X] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [X] The developer name is specified
- [X] The summary is completed
- [X] Ask for a review in communication channels

### Screenshots/Screencast
image
image

### CODE REVIEW

**Comment by jasonyu0705** [comment]
I had to combine 2 projects because I accidentally created 2 which is why there are not many commits

**Comment by elhagen13** [comment]
Just one minor fix! You need to change localhost to your deployed url for newComment.tsx component. Right now it won't let me post any comments. Everything else looks great though!

**Comment by jasonyu0705** [comment]
> Just one minor fix! You need to change localhost to your deployed url for newComment.tsx component. Right now it won't let me post any comments. Everything else looks great though!

Thanks for catching this!!

**Comment by elhagen13** [comment]
Great job! Congrats on finishing bootcamp :)

**Pull request closed without merging**
