### PR TITLE
Milestones 1, 2, 3a, 3b

### PR DESCRIPTION
**Pull request by amandayu255**
# Milestones: 1, 2, 3a, 3b
# Developer: Amanda Yu

### Pull Request Summary

This is the completed milestones 1, 2, 3a, 3b being submitted for review.

### Pull Request Checklist
- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit message follows our guidelines
- [x] The milestone number is specified
- [x] The developer name is specified
- [x] The summary is completed

### Reviewer Checklist  - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual template contributor, do not fill out the rest of the fields or check the boxes.

NOTE: Milestones can only be completed when all boxes are checked.

- [x] The code is fully reviewed
- [x] Meaningful feedback is given
- [x] Comment that you have reviewed the code
- [x] This box is checked

### CODE REVIEW

**Comment by amandayu255** [comment]
Updated to include milestone 2

**Comment by amandayu255** [comment]
Updated to include milestone 3a

**Comment by amandayu255** [comment]
Updated to include milestone 3b

**Review by ZealSV — COMMENTED** [review]
Great job! Code looks neat, to deploy as mentioned in slack, read the Vercel errors and fix them one by one and deployment should work! All features seem to be working correctly.

**Pull request closed without merging**
